import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TypesenseProvider } from "@/providers/typesenseProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  auth,
  children,
}: Readonly<{
  auth: React.ReactNode
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TypesenseProvider>
          <>
            {auth}
            {children}
          </>
        </TypesenseProvider>
        
      </body>
    </html>
  );
}
